//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAlex.GameOfLife.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowGrid {
            get {
                return ((bool)(this["ShowGrid"]));
            }
            set {
                this["ShowGrid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int UpdateInterval {
            get {
                return ((int)(this["UpdateInterval"]));
            }
            set {
                this["UpdateInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFD3D3D3")]
        public global::System.Windows.Media.Color GridlinesColor {
            get {
                return ((global::System.Windows.Media.Color)(this["GridlinesColor"]));
            }
            set {
                this["GridlinesColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFA9A9A9")]
        public global::System.Windows.Media.Color AlternatingGridlinesColor {
            get {
                return ((global::System.Windows.Media.Color)(this["AlternatingGridlinesColor"]));
            }
            set {
                this["AlternatingGridlinesColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#801E90FF")]
        public global::System.Windows.Media.Color SelectionColor {
            get {
                return ((global::System.Windows.Media.Color)(this["SelectionColor"]));
            }
            set {
                this["SelectionColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFF5F5F5")]
        public global::System.Windows.Media.Color BackColor {
            get {
                return ((global::System.Windows.Media.Color)(this["BackColor"]));
            }
            set {
                this["BackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Or")]
        public string PasteMode {
            get {
                return ((string)(this["PasteMode"]));
            }
            set {
                this["PasteMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0,0,0")]
        public global::System.Windows.Rect WindowBounds {
            get {
                return ((global::System.Windows.Rect)(this["WindowBounds"]));
            }
            set {
                this["WindowBounds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.WindowState WindowState {
            get {
                return ((global::System.Windows.WindowState)(this["WindowState"]));
            }
            set {
                this["WindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\r\n                  <ArrayOfColor xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-ins" +
            "tance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n                    <Color" +
            ">\r\n                      <A>255</A>\r\n                      <R>0</R>\r\n           " +
            "           <G>0</G>\r\n                      <B>255</B>\r\n                    </Col" +
            "or>\r\n                    <Color>\r\n                      <A>255</A>\r\n            " +
            "          <R>100</R>\r\n                      <G>254</G>\r\n                      <B" +
            ">0</B>\r\n                    </Color>\r\n                    <Color>\r\n             " +
            "         <A>255</A>\r\n                      <R>34</R>\r\n                      <G>2" +
            "40</G>\r\n                      <B>0</B>\r\n                    </Color>\r\n          " +
            "          <Color>\r\n                      <A>255</A>\r\n                      <R>0<" +
            "/R>\r\n                      <G>210</G>\r\n                      <B>0</B>\r\n         " +
            "           </Color>\r\n                    <Color>\r\n                      <A>255</" +
            "A>\r\n                      <R>0</R>\r\n                      <G>180</G>\r\n          " +
            "            <B>0</B>\r\n                    </Color>\r\n                    <Color>\r" +
            "\n                      <A>255</A>\r\n                      <R>0</R>\r\n             " +
            "         <G>150</G>\r\n                      <B>0</B>\r\n                    </Color" +
            ">\r\n                    <Color>\r\n                      <A>255</A>\r\n              " +
            "        <R>0</R>\r\n                      <G>120</G>\r\n                      <B>0</" +
            "B>\r\n                    </Color>\r\n                    <Color>\r\n                 " +
            "     <A>255</A>\r\n                      <R>0</R>\r\n                      <G>100</G" +
            ">\r\n                      <B>0</B>\r\n                    </Color>\r\n               " +
            "     <Color>\r\n                      <A>255</A>\r\n                      <R>0</R>\r\n" +
            "                      <G>70</G>\r\n                      <B>0</B>\r\n               " +
            "     </Color>\r\n                    <Color>\r\n                      <A>255</A>\r\n  " +
            "                    <R>115</R>\r\n                      <G>178</G>\r\n              " +
            "        <B>255</B>\r\n                    </Color>\r\n                    <Color>\r\n " +
            "                     <A>255</A>\r\n                      <R>80</R>\r\n              " +
            "        <G>158</G>\r\n                      <B>254</B>\r\n                    </Colo" +
            "r>\r\n                    <Color>\r\n                      <A>255</A>\r\n             " +
            "         <R>43</R>\r\n                      <G>137</G>\r\n                      <B>2" +
            "54</B>\r\n                    </Color>\r\n                    <Color>\r\n             " +
            "         <A>255</A>\r\n                      <R>0</R>\r\n                      <G>11" +
            "2</G>\r\n                      <B>248</B>\r\n                    </Color>\r\n         " +
            "           <Color>\r\n                      <A>255</A>\r\n                      <R>0" +
            "</R>\r\n                      <G>100</G>\r\n                      <B>225</B>\r\n      " +
            "              </Color>\r\n                    <Color>\r\n                      <A>25" +
            "5</A>\r\n                      <R>0</R>\r\n                      <G>94</G>\r\n        " +
            "              <B>206</B>\r\n                    </Color>\r\n                    <Col" +
            "or>\r\n                      <A>255</A>\r\n                      <R>0</R>\r\n         " +
            "             <G>77</G>\r\n                      <B>172</B>\r\n                    </" +
            "Color>\r\n                    <Color>\r\n                      <A>255</A>\r\n         " +
            "             <R>0</R>\r\n                      <G>63</G>\r\n                      <B" +
            ">140</B>\r\n                    </Color>\r\n                    <Color>\r\n           " +
            "           <A>255</A>\r\n                      <R>0</R>\r\n                      <G>" +
            "41</G>\r\n                      <B>92</B>\r\n                    </Color>\r\n         " +
            "         </ArrayOfColor>\r\n                ")]
        public global::System.Collections.Generic.List<System.Windows.Media.Color> StatesCellColors {
            get {
                return ((global::System.Collections.Generic.List<System.Windows.Media.Color>)(this["StatesCellColors"]));
            }
            set {
                this["StatesCellColors"] = value;
            }
        }
    }
}
